OnlineBookstore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineBookstore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineBookstore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        public CartSummaryViewComponent(Basket basketService)
        {
            basket = basketService;
        }
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

OnlineBookstore/Components/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineBookstore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineBookstore.Components
{
    public class CategoryViewComponent: ViewComponent
    {
        private IOnlineBookstoreRepository repo { get; set; }
        public CategoryViewComponent (IOnlineBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

OnlineBookstore/Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Book

<!--This is the shared layout for displaying the books-->
<div class="card card-outline-primary m-1 p-1 gap-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>

    <!--Changed the info to be dispayed witha  table-->
    <!--Added a comment for testing-->
    <table class="border-1">
        <thread class="font-weight-bolder">
            <tr>
                <td class="card-text p-1 text-decoration-underline col-1"><u>Author</u></td>
                <td class="card-text p-1 text-decoration-underline col-1"><u>Category</u></td>
                <td class="card-text p-1 text-decoration-underline col-1"><u>Publisher</u></td>
                <td class="card-text p-1 text-decoration-underline col-1"><u>Page Count</u></td>
                <td class="card-text p-1 text-decoration-underline col-1"></td>
            </tr>
        </thread>

        <tbody>
            <tr>
                <td class="card-text p-1 light">@Model.Author</td>
                <td class="card-text p-1">@Model.Category</td>
                <td class="card-text p-1">@Model.Publisher</td>
                <td class="card-text p-1">@Model.PageCount</td>
            </tr>
        </tbody>
    </table>


    <form method="post" asp-page="/Purchase">
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />


        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-right">Purchase</button>
        </span>
    </form>

</div>

OnlineBookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Book Store</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>


    <!--I added a background image and lowered the opacity. I had to mess with positioning a little to make it look right.-->
    <div style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-image: url('/lib/img/zaini-izzuddin-55btQzyDiO8-unsplash.jpg'); background-size: cover; z-index: -1; opacity: 0.4;">
        <div style="content: ''; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.2);"></div>
    </div>
    <div class="bg-dark text-white p-2">

    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:category></vc:category>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>

</body>
</html>